### ISSUE TITLE
Suggestion: Stop using a proxy in the Settings class

### ISSUE THREAD

**Issue by mythmon** [rehandalal/node-env-settings#2]
The proxy in Settings makes everything value only evaluate once. That's kind of nice, but proxies are complicated. I would either 

1) opt for an explict `.get()` method, so it is clear that what you're doing in more than just attribute lookup
2) or simplify Settings so that it is a (possibly cached) function that returns a normal object, instead of a lazily evaluated collection of things.

**Comment by rehandalal** [comment]
Yeah i think i'm gonna have a `composeSettings` function.
